### ISSUE TITLE
Hub Router - Support for aries-agent-rest features used by trustbloc components

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/mediator#8]
The hub-router project will be used by [issuer/rp adapters](https://github.com/trustbloc/edge-adapter) and [edge-agent](https://github.com/trustbloc/edge-agent). Currently, these projects are using [aries-agent-rest](https://github.com/trustbloc/edge-sandbox/blob/master/test/bdd/fixtures/demo/docker-compose-didcomm.yml#L11-L34). Internally, the hub-router will use aries-go-sdk. The features of aries-agent-agent (not provided by aries-sdk) thats used by trustbloc components need to be present/exposed in hub-router. 

The list includes:
- [x] Support to Generate router invitation #8 
- [x] Support to configure transports (http and websocket) #13 
- [x] Support to configure databases #2 
- [x] BDD tests #17
